
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[186] =
    {   0,
        0,    0,   53,   53,    0,    0,    0,    0,    0,    0,
       63,   61,   60,    1,   36,   45,   29,   35,   27,   37,
       38,   28,   43,   28,   29,   24,   44,   32,   33,   32,
       23,   41,   42,   35,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   39,   35,   40,   53,   52,
       53,   56,   56,   56,   50,   48,   50,   49,   50,    5,
        3,    2,    5,    4,   60,   32,   34,   27,   26,    0,
       30,    0,   31,   54,   51,    0,   24,   58,   58,   35,
       23,   23,   23,   23,   23,   23,   10,   23,   23,   23,
        6,   23,   23,   23,   23,   23,   23,   53,   53,   53,

       53,   56,   56,   55,   48,   47,    0,   46,    0,    2,
        0,    4,    0,    0,    0,   25,    0,   59,   59,   25,
       23,   23,   23,   23,   23,   23,   23,   23,    8,   12,
       23,   23,   23,   23,   23,   53,   53,    0,    0,    0,
       59,   25,   59,   25,   58,   23,   19,   13,   23,   23,
       23,    7,   23,   23,   23,   23,   16,   23,   53,   57,
       25,   11,   23,   23,   23,   14,   23,   23,   23,    9,
       57,   57,   23,   23,   15,   23,   17,   18,   57,   57,
       23,   20,   22,   21,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   29,   30,   31,   26,    1,   32,   33,   34,   35,

       36,   37,   26,   38,   39,   26,   40,   41,   26,   42,
       43,   44,   26,   45,   46,   47,   48,   49,   50,   26,
       26,   26,   51,   52,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[54] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        4,    1,    1,    5,    1,    1,    1,    6,    1,    7,
        8,    1,    1,    1,    1,    8,    8,    1,    4,    1,
        1,    7,    7,    8,    8,    8,    7,    8,    8,    8,
        8,    7,    8,    8,    7,    8,    7,    8,    7,    8,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[199] =
    {   0,
        0,    0,   51,   52,   53,   54,   55,   56,   67,   72,
      406,  407,   84,  407,  381,  407,  407,  394,   54,  407,
      407,   72,  407,   74,   52,   78,  407,   77,  379,   78,
        0,  407,  407,  407,  357,   72,   70,  360,   66,   74,
      355,  363,  348,  354,  358,  407,  343,  407,  365,  407,
      114,  390,  389,  372,  407,  407,  387,  407,  115,  407,
      119,  407,  386,  124,  129,  407,  407,   68,  407,    0,
      407,  118,  407,  407,  407,  120,  124,  370,  137,  407,
        0,  351,  340,  353,  342,  345,  333,  327,  327,  324,
        0,  315,  322,  309,  306,  294,  293,  268,  143,  267,

       79,  292,  290,  407,  407,  407,  287,  407,  159,  407,
      284,  164,  121,    0,  153,  157,  165,  174,  182,  196,
      252,  241,  229,  223,  237,  235,  231,  227,    0,    0,
      212,  203,  200,  211,  204,  208,  176,  186,  167,  204,
      213,  221,  235,    0,  243,  195,    0,    0,  190,  172,
      174,    0,  165,  161,  153,  162,    0,  154,  134,  245,
      258,    0,  134,  130,  132,    0,  118,  111,  111,    0,
      262,  271,   80,   65,    0,   34,    0,    0,  206,  223,
       26,    0,    0,    0,  407,  298,  306,  314,  322,  330,
      333,  335,  343,  351,  359,  364,  371,  376

    } ;

static const flex_int16_t yy_def[199] =
    {   0,
      185,    1,  186,  186,  187,  187,  188,  188,  189,  189,
      185,  185,  185,  185,  185,  185,  185,  185,  190,  185,
      185,  185,  185,  185,  185,  191,  185,  185,  185,  185,
      192,  185,  185,  185,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  185,  185,  185,  193,  185,
      193,  194,  194,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  195,  185,  196,
      185,  185,  185,  185,  185,  185,  191,  191,  191,  185,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  193,  193,  197,

      193,  194,  194,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  195,  198,  185,  185,  185,  185,  185,  191,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  197,  197,  185,  185,  185,
      185,  185,  185,  120,  120,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  197,  185,
      185,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      185,  185,  192,  192,  192,  192,  192,  192,  185,  185,
      192,  192,  192,  192,    0,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185

    } ;

static const flex_int16_t yy_nxt[461] =
    {   0,
       12,   13,   14,   13,   13,   13,   15,   16,   17,   18,
       19,   20,   21,   17,   22,   23,   24,   12,   25,   26,
       26,   27,   28,   29,   30,   31,   31,   32,   12,   33,
       34,   31,   35,   36,   37,   38,   39,   31,   40,   31,
       31,   31,   31,   41,   42,   43,   31,   31,   44,   45,
       46,   47,   48,   50,   50,   53,   53,   56,   56,   57,
       57,  184,   58,   58,   69,   74,   54,   54,   61,   62,
       75,   63,   64,   61,   62,  183,   63,   64,   69,   51,
       51,  100,   70,   59,   59,   65,   71,   65,   65,   65,
       73,   72,   72,   72,   72,   76,  114,   77,   77,   80,

       66,   66,   80,   83,   79,   86,   89,   99,   90,   84,
       91,  182,   87,   79,   85,   92,  100,  106,  101,  107,
      109,  110,  108,  111,  109,  109,  110,  181,  111,  112,
       65,   69,   65,   65,   65,  115,  100,   72,   72,  116,
      116,   76,   99,   77,   77,  100,  117,  101,  178,  114,
       79,  118,  177,  118,  119,  117,  120,  120,  176,   79,
      109,  110,  137,  111,  109,  109,  110,  175,  111,  112,
      174,   99,  138,  138,  139,  173,  116,  116,  100,  119,
      159,  119,  119,  140,  119,  119,  160,  160,  141,  170,
      141,  141,  140,  142,  142,  169,  141,  168,  141,  141,

      143,  141,  141,  139,  137,  138,  138,  167,  143,  143,
      141,  166,  141,  141,  165,  144,  144,  143,  118,  164,
      118,  119,  145,  161,  161,  180,  180,  141,  163,  141,
      141,  145,  141,  141,  162,  141,  137,  141,  141,  143,
      142,  142,  180,  180,  158,  157,  156,  143,  143,  143,
      155,  143,  143,  154,  143,  143,  143,  143,  153,  143,
      143,  143,  145,  145,  171,  171,  152,  151,  150,  149,
      143,  172,  141,  148,  141,  141,  147,  142,  142,  115,
      172,  171,  171,  146,  143,  179,  110,  179,  172,  106,
      180,  180,  103,  143,  103,  137,   99,  172,   49,   49,

       49,   49,   49,   49,   49,   49,   52,   52,   52,   52,
       52,   52,   52,   52,   55,   55,   55,   55,   55,   55,
       55,   55,   60,   60,   60,   60,   60,   60,   60,   60,
       68,  135,  134,   68,   68,   68,   68,   68,   78,   78,
       78,   81,   81,   98,  133,   98,   98,   98,   98,   98,
       98,  102,  102,  102,  102,  132,  102,  102,  102,  113,
      131,  130,  113,  113,  113,  113,  113,   68,  129,  128,
       68,  136,  127,  136,  136,  136,  136,  136,  136,  113,
      126,  125,  113,  124,  123,  122,  121,  185,  110,  105,
      104,  103,  103,   99,   67,   97,   96,   95,   94,   93,

       88,   82,   66,   67,   66,  185,   11,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185
    } ;

static const flex_int16_t yy_chk[461] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    5,    6,    7,    8,    7,
        8,  181,    7,    8,   19,   25,    5,    6,    9,    9,
       25,    9,    9,   10,   10,  176,   10,   10,   68,    3,
        4,  101,   19,    7,    8,   13,   22,   13,   13,   13,
       24,   22,   22,   24,   24,   26,   68,   26,   26,   28,

       28,   30,   30,   36,   26,   37,   39,  101,   39,   36,
       40,  174,   37,   26,   36,   40,   51,   59,   51,   59,
       61,   61,   59,   61,   61,   64,   64,  173,   64,   64,
       65,  113,   65,   65,   65,   72,  159,   72,   72,   76,
       76,   77,   51,   77,   77,   99,   76,   99,  169,  113,
       77,   79,  168,   79,   79,   76,   79,   79,  167,   77,
      109,  109,  159,  109,  109,  112,  112,  165,  112,  112,
      164,   99,  115,  115,  116,  163,  116,  116,  137,  117,
      137,  117,  117,  116,  117,  117,  139,  139,  118,  158,
      118,  118,  116,  118,  118,  156,  119,  155,  119,  119,

      118,  119,  119,  138,  137,  138,  138,  154,  119,  118,
      120,  153,  120,  120,  151,  120,  120,  119,  140,  150,
      140,  140,  120,  140,  140,  179,  179,  141,  149,  141,
      141,  120,  141,  141,  146,  142,  136,  142,  142,  141,
      142,  142,  180,  180,  135,  134,  133,  142,  141,  143,
      132,  143,  143,  131,  143,  143,  142,  145,  128,  145,
      145,  143,  145,  145,  160,  160,  127,  126,  125,  124,
      143,  160,  161,  123,  161,  161,  122,  161,  161,  171,
      160,  171,  171,  121,  161,  172,  111,  172,  171,  107,
      172,  172,  103,  161,  102,  100,   98,  171,  186,  186,

      186,  186,  186,  186,  186,  186,  187,  187,  187,  187,
      187,  187,  187,  187,  188,  188,  188,  188,  188,  188,
      188,  188,  189,  189,  189,  189,  189,  189,  189,  189,
      190,   97,   96,  190,  190,  190,  190,  190,  191,  191,
      191,  192,  192,  193,   95,  193,  193,  193,  193,  193,
      193,  194,  194,  194,  194,   94,  194,  194,  194,  195,
       93,   92,  195,  195,  195,  195,  195,  196,   90,   89,
      196,  197,   88,  197,  197,  197,  197,  197,  197,  198,
       87,   86,  198,   85,   84,   83,   82,   78,   63,   57,
       54,   53,   52,   49,   47,   45,   44,   43,   42,   41,

       38,   35,   29,   18,   15,   11,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[63] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "2005087.l"




#line 9 "2005087.l"
#include<bits/stdc++.h>
#include "2005087_SymbolTable.cpp"
#include "2005087_Utility.cpp"
#include "2005087_Node.h"
#include "y.tab.h"
using namespace std;
void yyerror(char *s);
extern SymbolTable sTable;
extern Utility util;
extern YYSTYPE yylval;
int startLineNo;
int tabNeeded=0;
int tabGot=0;
bool tabDeleted=false;

std::string singlelineComment = "";
std::string multilineComment = "";
std::string String="";
std::string stringToken="";

    char specialCharacter(char c){
    if (c == 'n') return '\n';
	else if (c == 't') return '\t';
	else if (c == 'a') return '\a';
	else if (c == 'f') return '\f';
	else if (c == 'b') return '\b';
	else if (c == 'v') return '\v';
	else if (c == 'r') return '\r';
	else if (c == '0') return '\0';
    else if (c=='\"') return '\"';
    else if (c=='\'') return '\'';
    else if (c == '\\') return '\\';
	else return c;
    }
  
    string currentCharacter(string s){
    string ret = "";
    
    for (int i = 0; i <s.size(); i++) {
        if (s[i] != '\\') {
            ret += s[i];
        } 
        else {
                char c = specialCharacter(s[i + 1]);
                ret += c;
                i++;
        }
    }
    return ret;
}

#line 691 "lex.yy.c"
#line 692 "lex.yy.c"

#define INITIAL 0
#define SLCOMMENT 1
#define MLCOMMENT 2
#define STRING 3
#define INDENTATION 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 76 "2005087.l"

#line 915 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 186 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 407 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 77 "2005087.l"
{
    tabDeleted=false;
    BEGIN(INDENTATION); 
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 81 "2005087.l"
{

}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 84 "2005087.l"
{
    tabGot++;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 87 "2005087.l"
{
    util.printWarning(": Warning, tab requrired but got space.", yylineno);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "2005087.l"
{
    int len = strlen(yytext);
    char lastChar = yytext[len - 1];
    if(lastChar=='}') {
        tabNeeded--;
        tabDeleted=true;
    }
    yyless(len - 1);
    if (tabGot != tabNeeded) {
        util.printWarning(": warning, "+std::to_string(tabNeeded) + " of tabs needed but got " + std::to_string(tabGot) + " tabs.", yylineno);
    }
    tabGot = 0;
    BEGIN(INITIAL);  
}   
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 105 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"IF"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return IF;
     }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 112 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"ELSE"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return ELSE;
     }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 119 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"FOR"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return FOR;
     }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 126 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"WHILE"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return WHILE;
     }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 133 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"DO"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return DO;
     }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 140 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"BREAK"));
        yylval.node->setStartLine(yylineno);
yylval.node->setEndLine(yylineno);
        return BREAK;
     }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 147 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"INT"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return INT;
     }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 154 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"CHAR"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return CHAR;
     }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 161 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"FLOAT"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return FLOAT;
     }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 168 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"DOUBLE"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return DOUBLE;
     }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 175 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"VOID"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return VOID;
     }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 182 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"RETURN"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return RETURN;  
     }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 189 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"SWITCH"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return SWITCH;
     }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 196 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"CASE"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return CASE;
     }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 203 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"DEFAULT"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return DEFAULT;
     }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 210 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"CONTINUE"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return CONTINUE;
     }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 217 "2005087.l"
{
        util.printKeyword(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"PRINTLN"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return PRINTLN;
     }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 226 "2005087.l"
{
        util.printAnother("ID",yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"ID"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return ID;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 234 "2005087.l"
{
        util.printAnother("CONST_INT",yytext,yylineno); 
        yylval.node=new Node(new SymbolInfo(yytext,"CONST_INT"),"","int");
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return CONST_INT;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 242 "2005087.l"
{
        util.printAnother("CONST_FLOAT",yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"CONST_FLOAT"),"","float");
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return CONST_FLOAT;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 250 "2005087.l"
{
        string current=yytext;
        current.erase(current.begin());
        current.pop_back(); 
        current=currentCharacter(current);
        if(current.length()==0){
            util.printError("EMPTY_CONST_CHAR","\'"+current+"\'",yylineno);
        }
        else if(current.length()==1){
            util.printAnother("CONST_CHAR",current,yylineno);
        }
        else{
            util.printError("MULTICHAR_CONST_CHAR","\'"+ current+"\'", yylineno);
        }
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 266 "2005087.l"
{
        string current = yytext;
        current.erase(current.begin()); 
        util.printError("UNFINISHED_CONST_CHAR", "\'" + current,yylineno);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 273 "2005087.l"
{
        util.printOperator("ADDOP",yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"ADDOP")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return ADDOP;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 280 "2005087.l"
{
        util.printOperator("MULOP",yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"MULOP")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return MULOP;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 287 "2005087.l"
{util.printOperator("INCOP",yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"INCOP")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return INCOP;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 292 "2005087.l"
{
        util.printOperator("DECOP",yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"DECOP")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return DECOP;   
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 299 "2005087.l"
{util.printOperator("RELOP",yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"RELOP")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return RELOP;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 305 "2005087.l"
{util.printOperator("ASSIGNOP",yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"ASSIGNOP")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return ASSIGNOP;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 310 "2005087.l"
{util.printOperator("LOGICOP",yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"LOGICOP"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno); 
        return LOGICOP;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 315 "2005087.l"
{
        util.printOperator("BITOP",yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"BITOP")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return BITOP;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 321 "2005087.l"
{util.printOperator("NOT",yytext,yylineno); 
        yylval.node=new Node(new SymbolInfo(yytext,"NOT")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return NOT;} 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 329 "2005087.l"
{
        util.printPunctuation(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"LPAREN")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return LPAREN;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 336 "2005087.l"
{
        util.printPunctuation(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"RPAREN")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return RPAREN;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 343 "2005087.l"
{
        util.printPunctuation(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"LCURL")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        tabNeeded++;
        return LCURL;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 351 "2005087.l"
{
        util.printPunctuation(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"RCURL")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        if(!tabDeleted){
            tabNeeded--;
        }
        return RCURL;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 361 "2005087.l"
{
        util.printPunctuation(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"LSQUARE")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return LSQUARE;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 368 "2005087.l"
{
        util.printPunctuation(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"RSQUARE"));
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno); 
        return RSQUARE;
 }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 375 "2005087.l"
{
        util.printPunctuation(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"COMMA")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return COMMA;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 382 "2005087.l"
{
        util.printPunctuation(yytext,yylineno);
        yylval.node=new Node(new SymbolInfo(yytext,"SEMICOLON")); 
        yylval.node->setStartLine(yylineno);
        yylval.node->setEndLine(yylineno);
        return SEMICOLON;
 }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 391 "2005087.l"
{
        BEGIN(STRING);
        startLineNo = yylineno;
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 396 "2005087.l"
{
        util.printError("UNFINISHED_STRING", "\"" + String, yylineno-1);
        String = "";
        stringToken="";
        BEGIN(INITIAL);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 403 "2005087.l"
{
        String += yytext;
        stringToken+=yytext;
}
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 408 "2005087.l"
{
        String += yytext;
}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 412 "2005087.l"
{
        util.printError("UNFINISHED_STRING", "\"" + String, yylineno-1);
        String = "";
        stringToken="";
        BEGIN(INITIAL);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 419 "2005087.l"
{
        if (startLineNo == yylineno){
            util.printAnother("SINGLE LINE STRING", "\"" + String + "\"", startLineNo);
        }
            
        else{
            util.printAnother("MULTI LINE STRING", "\"" + String + "\"", startLineNo);
        }
            
        String = "";
        stringToken="";
        BEGIN(INITIAL);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 433 "2005087.l"
{
        String += yytext;
        stringToken+=yytext;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 438 "2005087.l"
{
        BEGIN(SLCOMMENT);
        startLineNo= yylineno;
}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 443 "2005087.l"
{
        BEGIN(INITIAL);
        singlelineComment = singlelineComment.substr(0, singlelineComment.length());
        util.printSingleLineComment(singlelineComment, startLineNo);
        singlelineComment = "";
}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 450 "2005087.l"
{
        singlelineComment += yytext;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 454 "2005087.l"
{
        BEGIN(MLCOMMENT);
        startLineNo= yylineno;
}
	YY_BREAK
case YY_STATE_EOF(MLCOMMENT):
#line 459 "2005087.l"
{
        BEGIN(INITIAL);
        util.printError("UNFINISHED_COMMENT","/*"+multilineComment, yylineno);
        multilineComment="";
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 465 "2005087.l"
{
        BEGIN(INITIAL);
        util.printMultiLineComment(multilineComment, startLineNo);
        multilineComment = "";
}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 471 "2005087.l"
{
        multilineComment+=yytext;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 476 "2005087.l"
{
        util.printError("TOO_MANY_DECIMAL_POINTS", yytext, yylineno);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 479 "2005087.l"
{
        util.printError("INVALID_ID_SUFFIX_NUM_PREFIX", yytext, yylineno);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 482 "2005087.l"
{
        util.printError("ILLFORMED_NUMBER",yytext,yylineno);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 485 "2005087.l"
{
    // Skip whitespace
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SLCOMMENT):
case YY_STATE_EOF(INDENTATION):
#line 488 "2005087.l"
{return 0;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 489 "2005087.l"
{
        util.printError("UNRECOGNIZED_CHAR", yytext, yylineno);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 492 "2005087.l"
ECHO;
	YY_BREAK
#line 1635 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 186 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 186 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 185);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 492 "2005087.l"


